test_task:
  freebsd_instance:
    matrix:
      - image_family: freebsd-12-0
      - image_family: freebsd-13-0-snap
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock || echo 'nope'
  before_cache_script: rm -rf $CARGO_HOME/registry/index
  install_script: pkg install -y rust
  build_script: cargo build --verbose
  test_script: cargo run --verbose --example info
